"""
Python 3 Interface of erl_covariance
"""
from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['CovarianceD', 'CovarianceF', 'YamlableBase']
class CovarianceD:
    class Setting(YamlableBase):
        def __init__(self) -> None:
            ...
        @property
        def scale(self) -> float:
            ...
        @scale.setter
        def scale(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def scale_mix(self) -> float:
            ...
        @scale_mix.setter
        def scale_mix(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def x_dim(self) -> int:
            ...
        @x_dim.setter
        def x_dim(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
    def compute_ktest(self, mat_x1: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], num_samples: typing.SupportsInt | typing.SupportsIndex, mat_x2: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], num_queries: typing.SupportsInt | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    def compute_ktest_with_gradient(self, mat_x1: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], num_samples: typing.SupportsInt | typing.SupportsIndex, vec_grad1_flags: typing.Annotated[numpy.typing.NDArray[numpy.int64], "[m, 1]"], mat_x2: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], num_queries: typing.SupportsInt | typing.SupportsIndex, predict_gradient: bool) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]"]:
        ...
    @typing.overload
    def compute_ktrain(self, mat_x: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], num_samples: typing.SupportsInt | typing.SupportsIndex, mat_alpha: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> dict:
        ...
    @typing.overload
    def compute_ktrain(self, mat_x: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], vec_var_y: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"], num_samples: typing.SupportsInt | typing.SupportsIndex, mat_alpha: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> dict:
        ...
    @typing.overload
    def compute_ktrain_with_gradient(self, mat_x: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], num_samples: typing.SupportsInt | typing.SupportsIndex, vec_grad_flags: typing.Annotated[numpy.typing.ArrayLike, numpy.int64, "[m, 1]"], mat_alpha: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> dict:
        ...
    @typing.overload
    def compute_ktrain_with_gradient(self, mat_x: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], num_samples: typing.SupportsInt | typing.SupportsIndex, vec_grad_flags: typing.Annotated[numpy.typing.ArrayLike, numpy.int64, "[m, 1]"], vec_var_x: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"], vec_var_y: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"], vec_var_grad: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"], mat_alpha: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[m, n]"]) -> dict:
        ...
    def get_minimum_ktest_size(self, num_train_samples: typing.SupportsInt | typing.SupportsIndex, num_train_samples_with_gradient: typing.SupportsInt | typing.SupportsIndex, num_gradient_dimensions: typing.SupportsInt | typing.SupportsIndex, num_test_queries: typing.SupportsInt | typing.SupportsIndex, predict_gradient: bool) -> tuple[int, int]:
        ...
    def get_minimum_ktrain_size(self, num_samples: typing.SupportsInt | typing.SupportsIndex, num_samples_with_gradient: typing.SupportsInt | typing.SupportsIndex, num_gradient_dimensions: typing.SupportsInt | typing.SupportsIndex) -> tuple[int, int]:
        ...
    @property
    def setting(self) -> CovarianceD.Setting:
        ...
    @property
    def type(self) -> str:
        ...
class CovarianceF:
    class Setting(YamlableBase):
        def __init__(self) -> None:
            ...
        @property
        def scale(self) -> float:
            ...
        @scale.setter
        def scale(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def scale_mix(self) -> float:
            ...
        @scale_mix.setter
        def scale_mix(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def x_dim(self) -> int:
            ...
        @x_dim.setter
        def x_dim(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
    def compute_ktest(self, mat_x1: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"], num_samples: typing.SupportsInt | typing.SupportsIndex, mat_x2: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"], num_queries: typing.SupportsInt | typing.SupportsIndex) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]"]:
        ...
    def compute_ktest_with_gradient(self, mat_x1: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"], num_samples: typing.SupportsInt | typing.SupportsIndex, vec_grad1_flags: typing.Annotated[numpy.typing.NDArray[numpy.int64], "[m, 1]"], mat_x2: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"], num_queries: typing.SupportsInt | typing.SupportsIndex, predict_gradient: bool) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]"]:
        ...
    @typing.overload
    def compute_ktrain(self, mat_x: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"], num_samples: typing.SupportsInt | typing.SupportsIndex, mat_alpha: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"]) -> dict:
        ...
    @typing.overload
    def compute_ktrain(self, mat_x: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"], vec_var_y: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"], num_samples: typing.SupportsInt | typing.SupportsIndex, mat_alpha: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"]) -> dict:
        ...
    @typing.overload
    def compute_ktrain_with_gradient(self, mat_x: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"], num_samples: typing.SupportsInt | typing.SupportsIndex, vec_grad_flags: typing.Annotated[numpy.typing.ArrayLike, numpy.int64, "[m, 1]"], mat_alpha: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"]) -> dict:
        ...
    @typing.overload
    def compute_ktrain_with_gradient(self, mat_x: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"], num_samples: typing.SupportsInt | typing.SupportsIndex, vec_grad_flags: typing.Annotated[numpy.typing.ArrayLike, numpy.int64, "[m, 1]"], vec_var_x: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"], vec_var_y: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"], vec_var_grad: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, 1]"], mat_alpha: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[m, n]"]) -> dict:
        ...
    def get_minimum_ktest_size(self, num_train_samples: typing.SupportsInt | typing.SupportsIndex, num_train_samples_with_gradient: typing.SupportsInt | typing.SupportsIndex, num_gradient_dimensions: typing.SupportsInt | typing.SupportsIndex, num_test_queries: typing.SupportsInt | typing.SupportsIndex, predict_gradient: bool) -> tuple[int, int]:
        ...
    def get_minimum_ktrain_size(self, num_samples: typing.SupportsInt | typing.SupportsIndex, num_samples_with_gradient: typing.SupportsInt | typing.SupportsIndex, num_gradient_dimensions: typing.SupportsInt | typing.SupportsIndex) -> tuple[int, int]:
        ...
    @property
    def setting(self) -> CovarianceF.Setting:
        ...
    @property
    def type(self) -> str:
        ...
class YamlableBase:
    def __str__(self) -> str:
        ...
    def as_yaml_file(self, yaml_file: str) -> None:
        ...
    def as_yaml_string(self) -> str:
        ...
    def from_command_line(self, args: collections.abc.Sequence[str]) -> bool:
        ...
    def from_yaml_file(self, yaml_file: str, base_config_field: str) -> bool:
        ...
    def from_yaml_string(self, yaml_str: str) -> bool:
        ...
